### ISSUE TITLE
Grove-Multichannel-Gas-Sensor-V2 Compatibility

### ISSUE THREAD

**Issue by elloza** [ostaquet/Arduino-Grove-MultichannelGasSensor-driver#1]
Hello 

First of all congratulations for the work. I am trying to make a in Python of the [Gas Sensor V2 (Multichannel) sensor](https://wiki.seeedstudio.com/Grove-Multichannel-Gas-Sensor-V2/) and I would like to know if your library is compatible with that sensor.

Thank you very much.

**Comment by ostaquet** [comment]
At first reading, the library is not compatible with the sensor you mentioned. The library is designed around the MiCS chipset. However, your module seems to embed 4 sensors driven by a STM MCU.

It is time to write a new driver 😉

**Comment by elloza** [comment]
Thanks for the quick response 😀

I found this library which seems to be the official one:

[Seeed-Studio/Seeed_Arduino_MultiGas](https://github.com/Seeed-Studio/Seeed_Arduino_MultiGas)

But the port I currently have in [Python doesn't seem to be working.](https://github.com/Seeed-Studio/Seeed_Arduino_MultiGas/issues/4)

Thank you very much in any case!
